"""Physical constants and configuration values."""

import os
from datetime import timedelta
from io import StringIO

import pandas as pd

RAW_DATA_FILE_TEMPLATE = "%t-raw-data.csv"
CALCULATED_DATA_FILE_TEMPLATE = "%t-computed.csv"
EXTRACTED_DATA_FILE_TEMPLATE = "extracted%T.csv"
MAX_AGE = timedelta(weeks=1)

DATA_DIR = os.path.join(
    os.path.dirname(os.path.dirname(os.path.dirname(__file__))), "data"
)

SCRIPT_DIR = os.path.join(
    os.path.dirname(os.path.dirname(os.path.dirname(__file__))), "scripts"
)

G = 6.67430e-11
M_JUP_KG = 1.89813e27
R_JUP_M = 7.14920e7
G_EARTH = 9.80665

DM_AB_KG = 5.0e25
DM_BC_KG = 1.0e27

DM_GRAVITY: dict[str, tuple[float, float]] = {
    "A": (2e-10, 0.4282),
    "B": (14937, -0.1219),
    "C": (4e-28, 1.0482),
}

EXOPLANET_ARCHIVE_TAP_BASE = "https://exoplanetarchive.ipac.caltech.edu/TAP/sync"

USUAL_PS_WHERE = "pl_bmassj IS NOT NULL AND pl_radj IS NOT NULL AND pl_dens IS NOT NULL"

USUAL_PSCOMPPARS_WHERE = (
    "pl_bmassj IS NOT NULL AND pl_radj IS NOT NULL AND pl_dens IS NOT NULL"
)

ALL_PSCOMPPARS_COLUMNS: list[str] = [
    "objectid",
    "pl_name",
    "pl_letter",
    "hostid",
    "hostname",
    "hd_name",
    "hip_name",
    "tic_id",
    "disc_pubdate",
    "disc_year",
    "disc_method",
    "discoverymethod",
    "disc_locale",
    "disc_facility",
    "disc_instrument",
    "disc_telescope",
    "disc_refname",
    "ra",
    "raerr1",
    "raerr2",
    "rasymerr",
    "rastr",
    "ra_solnid",
    "ra_reflink",
    "dec",
    "decerr1",
    "decerr2",
    "decsymerr",
    "decstr",
    "dec_solnid",
    "dec_reflink",
    "glon",
    "glonerr1",
    "glonerr2",
    "glonsymerr",
    "glonstr",
    "glon_solnid",
    "glon_reflink",
    "glat",
    "glaterr1",
    "glaterr2",
    "glatsymerr",
    "glatstr",
    "glat_solnid",
    "glat_reflink",
    "elon",
    "elonerr1",
    "elonerr2",
    "elonsymerr",
    "elonstr",
    "elon_solnid",
    "elon_reflink",
    "elat",
    "elaterr1",
    "elaterr2",
    "elatsymerr",
    "elat_solnid",
    "elat_reflink",
    "elatstr",
    "pl_orbper",
    "pl_orbpererr1",
    "pl_orbpererr2",
    "pl_orbpersymerr",
    "pl_orbperlim",
    "pl_orbperstr",
    "pl_orbperformat",
    "pl_orbper_solnid",
    "pl_orbper_reflink",
    "pl_orblpererr1",
    "pl_orblper",
    "pl_orblpererr2",
    "pl_orblpersymerr",
    "pl_orblperlim",
    "pl_orblperstr",
    "pl_orblperformat",
    "pl_orblper_solnid",
    "pl_orblper_reflink",
    "pl_orbsmax",
    "pl_orbsmaxerr1",
    "pl_orbsmaxerr2",
    "pl_orbsmaxsymerr",
    "pl_orbsmaxlim",
    "pl_orbsmaxstr",
    "pl_orbsmaxformat",
    "pl_orbsmax_solnid",
    "pl_orbsmax_reflink",
    "pl_orbincl",
    "pl_orbinclerr1",
    "pl_orbinclerr2",
    "pl_orbinclsymerr",
    "pl_orbincllim",
    "pl_orbinclstr",
    "pl_orbinclformat",
    "pl_orbincl_solnid",
    "pl_orbincl_reflink",
    "pl_orbtper",
    "pl_orbtpererr1",
    "pl_orbtpererr2",
    "pl_orbtpersymerr",
    "pl_orbtperlim",
    "pl_orbtperstr",
    "pl_orbtperformat",
    "pl_orbtper_solnid",
    "pl_orbtper_reflink",
    "pl_orbeccen",
    "pl_orbeccenerr1",
    "pl_orbeccenerr2",
    "pl_orbeccensymerr",
    "pl_orbeccenlim",
    "pl_orbeccenstr",
    "pl_orbeccenformat",
    "pl_orbeccen_solnid",
    "pl_orbeccen_reflink",
    "pl_eqt",
    "pl_eqterr1",
    "pl_eqterr2",
    "pl_eqtsymerr",
    "pl_eqtlim",
    "pl_eqtstr",
    "pl_eqtformat",
    "pl_eqt_solnid",
    "pl_eqt_reflink",
    "pl_occdep",
    "pl_occdeperr1",
    "pl_occdeperr2",
    "pl_occdepsymerr",
    "pl_occdeplim",
    "pl_occdepstr",
    "pl_occdepformat",
    "pl_occdep_solnid",
    "pl_occdep_reflink",
    "pl_insol",
    "pl_insolerr1",
    "pl_insolerr2",
    "pl_insolsymerr",
    "pl_insollim",
    "pl_insolstr",
    "pl_insolformat",
    "pl_insol_solnid",
    "pl_insol_reflink",
    "pl_dens",
    "pl_denserr1",
    "sy_umagerr1",
    "sy_umagerr2",
    "sy_umaglim",
    "sy_umagsymerr",
    "sy_umagstr",
    "sy_umagformat",
    "sy_umag_solnid",
    "sy_umag_reflink",
    "sy_rmag",
    "sy_rmagerr1",
    "sy_rmagerr2",
    "sy_rmaglim",
    "sy_rmagsymerr",
    "sy_rmagstr",
    "sy_rmagformat",
    "sy_rmag_solnid",
    "sy_rmag_reflink",
    "sy_imag",
    "sy_imagerr1",
    "sy_imagerr2",
    "sy_imaglim",
    "sy_imagsymerr",
    "sy_imagstr",
    "sy_imagformat",
    "sy_imag_solnid",
    "sy_imag_reflink",
    "sy_zmag",
    "sy_zmagerr1",
    "sy_zmagerr2",
    "sy_zmaglim",
    "sy_zmagsymerr",
    "sy_zmagstr",
    "sy_zmagformat",
    "sy_zmag_solnid",
    "sy_zmag_reflink",
    "sy_w1mag",
    "sy_w1magerr1",
    "sy_w1magerr2",
    "sy_w1maglim",
    "sy_w1magsymerr",
    "sy_w1magstr",
    "sy_w1magformat",
    "sy_w1mag_solnid",
    "sy_w1mag_reflink",
    "sy_w2mag",
    "sy_w2magerr1",
    "sy_w2magerr2",
    "sy_w2maglim",
    "sy_w2magsymerr",
    "sy_w2magstr",
    "sy_w2magformat",
    "sy_w2mag_solnid",
    "sy_w2mag_reflink",
    "sy_w3mag",
    "sy_w3magerr1",
    "sy_w3magerr2",
    "sy_w3maglim",
    "sy_w3magsymerr",
    "sy_w3magstr",
    "sy_w3magformat",
    "sy_w3mag_solnid",
    "sy_w3mag_reflink",
    "sy_w4mag",
    "sy_w4magerr1",
    "sy_w4magerr2",
    "sy_w4maglim",
    "sy_w4magsymerr",
    "sy_w4magstr",
    "sy_w4magformat",
    "sy_w4mag_solnid",
    "sy_w4mag_reflink",
    "sy_gmag",
    "sy_gmagerr1",
    "sy_gmagerr2",
    "sy_gmaglim",
    "sy_gmagsymerr",
    "sy_gmagstr",
    "sy_gmagformat",
    "sy_gmag_solnid",
    "sy_gmag_reflink",
    "sy_gaiamag",
    "sy_gaiamagerr1",
    "sy_gaiamagerr2",
    "sy_gaiamaglim",
    "sy_gaiamagsymerr",
    "sy_gaiamagstr",
    "sy_gaiamagformat",
    "sy_gaiamag_solnid",
    "sy_gaiamag_reflink",
    "sy_tmag",
    "sy_tmagerr1",
    "sy_tmagerr2",
    "sy_tmaglim",
    "sy_tmagsymerr",
    "sy_tmagstr",
    "sy_tmagformat",
    "sy_tmag_solnid",
    "sy_tmag_reflink",
    "sy_name",
    "pl_controv_flag",
    "pl_orbtper_systemref",
    "pl_tranmid_systemref",
    "st_metratio",
    "st_spectype",
    "st_spectype_solnid",
    "st_spectype_reflink",
    "sy_plxlim",
    "sy_kepmag",
    "sy_kepmagerr1",
    "sy_kepmagerr2",
    "sy_kepmaglim",
    "sy_kepmagsymerr",
    "sy_kepmagstr",
    "sy_kepformat",
    "sy_kepmag_solnid",
    "sy_kepmag_reflink",
    "st_rotp",
    "st_rotperr1",
    "st_rotperr2",
    "st_rotpsymerr",
    "st_rotplim",
    "st_rotpstr",
    "st_rotpformat",
    "st_rotp_solnid",
    "st_rotp_reflink",
    "pl_projobliq",
    "pl_projobliqerr1",
    "pl_projobliqerr2",
    "pl_projobliqsymerr",
    "pl_projobliqlim",
    "pl_projobliqstr",
    "pl_projobliqformat",
    "pl_denserr2",
    "pl_denssymerr",
    "pl_denslim",
    "pl_densstr",
    "pl_densformat",
    "pl_dens_solnid",
    "pl_dens_reflink",
    "pl_trandep",
    "pl_trandeperr1",
    "pl_trandeperr2",
    "pl_trandepsymerr",
    "pl_trandeplim",
    "pl_trandepstr",
    "pl_trandepformat",
    "pl_trandep_solnid",
    "pl_trandep_reflink",
    "pl_tranmid",
    "pl_tranmiderr1",
    "pl_tranmiderr2",
    "pl_tranmidsymerr",
    "pl_tranmidlim",
    "pl_tranmidstr",
    "pl_tranmidformat",
    "pl_tranmid_solnid",
    "pl_tranmid_reflink",
    "pl_trandur",
    "pl_trandurerr1",
    "pl_trandurerr2",
    "pl_trandursymerr",
    "pl_trandurlim",
    "pl_trandurstr",
    "pl_trandurformat",
    "pl_trandur_solnid",
    "pl_trandur_reflink",
    "pl_rvamp",
    "pl_rvamperr1",
    "pl_rvamperr2",
    "pl_rvampsymerr",
    "pl_rvamplim",
    "pl_rvampstr",
    "pl_rvampformat",
    "pl_rvamp_solnid",
    "pl_rvamp_reflink",
    "pl_radj",
    "pl_radjerr1",
    "pl_radjerr2",
    "pl_radjsymerr",
    "pl_radjlim",
    "pl_radjstr",
    "pl_radjformat",
    "pl_radj_solnid",
    "pl_radj_reflink",
    "pl_rade",
    "pl_radeerr1",
    "pl_radeerr2",
    "pl_radesymerr",
    "pl_radelim",
    "pl_radestr",
    "pl_radeformat",
    "pl_rade_solnid",
    "pl_rade_reflink",
    "pl_ratror",
    "pl_ratrorerr1",
    "pl_ratrorerr2",
    "pl_ratrorsymerr",
    "pl_ratrorlim",
    "pl_ratrorstr",
    "pl_ratrorformat",
    "pl_ratror_solnid",
    "pl_ratror_reflink",
    "pl_ratdor",
    "pl_trueobliq",
    "pl_trueobliqerr1",
    "pl_trueobliqerr2",
    "pl_trueobliqsymerr",
    "pl_trueobliqlim",
    "pl_trueobliqstr",
    "pl_trueobliqformat",
    "pl_trueobliq_solnid",
    "pl_trueobliq_reflink",
    "st_log_rhk",
    "st_log_rhkerr1",
    "st_log_rhkerr2",
    "st_log_rhksymerr",
    "st_log_rhklim",
    "st_log_rhkstr",
    "st_log_rhkformat",
    "st_log_rhk_solnid",
    "st_log_rhk_reflink",
    "st_metn",
    "sy_icmag",
    "sy_icmagerr1",
    "sy_icmagerr2",
    "sy_icmagsymerr",
    "sy_icmagstr",
    "sy_icmagformat",
    "sy_icmag_solnid",
    "sy_icmag_reflink",
    "pl_pubdate",
    "dkin_flag",
    "pl_ratdorerr1",
    "pl_ratdorerr2",
    "pl_ratdorsymerr",
    "pl_ratdorlim",
    "pl_ratdorstr",
    "pl_ratdorformat",
    "pl_ratdor_solnid",
    "pl_ratdor_reflink",
    "pl_imppar",
    "pl_impparerr1",
    "pl_impparerr2",
    "pl_impparsymerr",
    "pl_impparlim",
    "pl_impparstr",
    "pl_impparformat",
    "pl_imppar_solnid",
    "pl_imppar_reflink",
    "pl_cmassj",
    "pl_cmassjerr1",
    "pl_cmassjerr2",
    "pl_cmassjsymerr",
    "pl_cmassjlim",
    "pl_cmassjstr",
    "pl_cmassjformat",
    "pl_cmassj_solnid",
    "pl_cmassj_reflink",
    "pl_cmasse",
    "pl_cmasseerr1",
    "pl_cmasseerr2",
    "pl_cmassesymerr",
    "pl_cmasselim",
    "pl_cmassestr",
    "pl_cmasseformat",
    "pl_cmasse_solnid",
    "pl_cmasse_reflink",
    "pl_massj",
    "pl_massjerr1",
    "pl_massjerr2",
    "pl_massjsymerr",
    "pl_massjlim",
    "pl_massjstr",
    "pl_massjformat",
    "pl_massj_solnid",
    "pl_massj_reflink",
    "pl_masse",
    "pl_masseerr1",
    "pl_masseerr2",
    "pl_massesymerr",
    "pl_masselim",
    "pl_massestr",
    "pl_masseformat",
    "pl_masse_solnid",
    "pl_masse_reflink",
    "pl_bmassj",
    "pl_bmassjerr1",
    "pl_bmassjerr2",
    "pl_bmassjsymerr",
    "pl_bmassjlim",
    "pl_bmassjstr",
    "pl_bmassjformat",
    "pl_bmassj_solnid",
    "pl_bmassj_reflink",
    "pl_bmasse",
    "pl_bmasseerr1",
    "pl_bmasseerr2",
    "pl_bmassesymerr",
    "pl_bmasselim",
    "pl_bmassestr",
    "pl_bmasseformat",
    "pl_bmasse_solnid",
    "pl_bmasse_reflink",
    "pl_bmassprov",
    "pl_msinij",
    "pl_msinijerr1",
    "pl_msinijerr2",
    "pl_msinijsymerr",
    "pl_msinijlim",
    "pl_msinijstr",
    "pl_msinijformat",
    "pl_msinij_solnid",
    "pl_msinij_reflink",
    "pl_msinie",
    "pl_msinieerr1",
    "pl_msinieerr2",
    "pl_msiniesymerr",
    "pl_msinielim",
    "pl_msiniestr",
    "pl_msinieformat",
    "pl_msinie_solnid",
    "pl_msinie_reflink",
    "st_teff",
    "st_tefferr1",
    "st_tefferr2",
    "st_teffsymerr",
    "st_tefflim",
    "st_teffstr",
    "st_teffformat",
    "st_teff_solnid",
    "st_teff_reflink",
    "st_met",
    "st_meterr1",
    "st_meterr2",
    "st_metsymerr",
    "st_metlim",
    "st_metstr",
    "st_metformat",
    "st_met_solnid",
    "st_met_reflink",
    "st_radv",
    "st_radverr1",
    "st_radverr2",
    "st_radvsymerr",
    "st_radvlim",
    "st_radvstr",
    "st_radvformat",
    "st_radv_solnid",
    "st_radv_reflink",
    "st_vsin",
    "st_vsinerr1",
    "st_vsinerr2",
    "st_vsinsymerr",
    "st_vsinlim",
    "st_vsinstr",
    "st_vsin_solnid",
    "st_vsin_reflink",
    "st_vsinformat",
    "st_lum",
    "st_lumerr1",
    "st_lumerr2",
    "st_lumsymerr",
    "st_lumlim",
    "st_lumstr",
    "st_lumformat",
    "st_lum_solnid",
    "st_lum_reflink",
    "st_logg",
    "st_loggerr1",
    "st_loggerr2",
    "st_loggsymerr",
    "st_logglim",
    "st_loggstr",
    "st_loggformat",
    "st_logg_solnid",
    "st_logg_reflink",
    "st_age",
    "st_ageerr1",
    "st_ageerr2",
    "st_agesymerr",
    "st_agelim",
    "st_agestr",
    "st_ageformat",
    "st_age_solnid",
    "st_age_reflink",
    "st_mass",
    "st_masserr1",
    "st_masserr2",
    "st_masssymerr",
    "st_masslim",
    "st_massstr",
    "st_massformat",
    "st_mass_solnid",
    "st_mass_reflink",
    "st_dens",
    "st_denserr1",
    "st_denserr2",
    "st_denssymerr",
    "st_denslim",
    "st_densstr",
    "st_densformat",
    "st_dens_solnid",
    "st_dens_reflink",
    "st_rad",
    "st_raderr1",
    "st_raderr2",
    "st_radsymerr",
    "st_radlim",
    "st_radstr",
    "st_radformat",
    "st_rad_solnid",
    "st_rad_reflink",
    "systemid",
    "ttv_flag",
    "ptv_flag",
    "tran_flag",
    "rv_flag",
    "ast_flag",
    "obm_flag",
    "micro_flag",
    "etv_flag",
    "ima_flag",
    "pul_flag",
    "disc_refid",
    "sy_snum",
    "sy_pnum",
    "sy_mnum",
    "st_nphot",
    "st_nrvc",
    "st_nspec",
    "pl_nespec",
    "pl_ntranspec",
    "pl_nnotes",
    "sy_pm",
    "sy_pmerr1",
    "sy_pmerr2",
    "sy_pmsymerr",
    "sy_pmlim",
    "sy_pmstr",
    "sy_pmformat",
    "sy_pm_solnid",
    "sy_pm_reflink",
    "sy_pmra",
    "sy_pmraerr1",
    "sy_pmraerr2",
    "sy_pmrasymerr",
    "sy_pmralim",
    "sy_pmrastr",
    "sy_pmraformat",
    "sy_pmra_solnid",
    "sy_pmra_reflink",
    "sy_pmdec",
    "sy_pmdecerr1",
    "sy_pmdecerr2",
    "sy_pmdecsymerr",
    "sy_pmdeclim",
    "sy_pmdecstr",
    "sy_pmdecformat",
    "sy_pmdec_solnid",
    "sy_pmdec_reflink",
    "sy_plx",
    "sy_plxerr1",
    "sy_plxerr2",
    "sy_plxsymerr",
    "sy_plxstr",
    "sy_plxformat",
    "sy_plx_solnid",
    "sy_plx_reflink",
    "sy_dist",
    "sy_disterr1",
    "sy_disterr2",
    "sy_distsymerr",
    "sy_distlim",
    "sy_diststr",
    "sy_distformat",
    "sy_dist_solnid",
    "sy_dist_reflink",
    "sy_bmag",
    "sy_bmagerr1",
    "sy_bmagerr2",
    "sy_bmaglim",
    "sy_bmagsymerr",
    "sy_bmagstr",
    "sy_bmagformat",
    "sy_bmag_solnid",
    "sy_bmag_reflink",
    "sy_vmag",
    "sy_vmagerr1",
    "sy_vmagerr2",
    "sy_vmaglim",
    "sy_vmagsymerr",
    "sy_vmagstr",
    "sy_vmagformat",
    "sy_vmag_solnid",
    "sy_vmag_reflink",
    "sy_jmag",
    "sy_jmagerr1",
    "sy_jmagerr2",
    "sy_jmaglim",
    "sy_jmagsymerr",
    "sy_jmagstr",
    "sy_jmagformat",
    "sy_jmag_solnid",
    "sy_jmag_reflink",
    "sy_hmag",
    "sy_hmagerr1",
    "sy_hmagerr2",
    "sy_hmaglim",
    "sy_hmagsymerr",
    "sy_hmagstr",
    "sy_hmagformat",
    "sy_hmag_solnid",
    "sy_hmag_reflink",
    "sy_kmag",
    "sy_kmagerr1",
    "sy_kmagerr2",
    "sy_kmaglim",
    "sy_kmagsymerr",
    "sy_kmagstr",
    "sy_kmagformat",
    "sy_kmag_solnid",
    "sy_kmag_reflink",
    "sy_umag",
    "pl_projobliq_solnid",
    "pl_projobliq_reflink",
    "x",
    "y",
    "z",
    "htm20",
    "gaia_dr2_id",
    "gaia_dr3_id",
    "cb_flag",
    "pl_angsep",
    "pl_angseperr1",
    "pl_angseperr2",
    "pl_angseplim",
    "pl_angsepformat",
    "pl_angsepstr",
    "pl_angsepsymerr",
    "pl_angsep_reflink",
    "pl_ndispec",
]

ALL_PS_COLUMNS = [
    "pl_name",
    "pl_letter",
    "hostname",
    "hd_name",
    "hip_name",
    "tic_id",
    "gaia_dr2_id",
    "gaia_dr3_id",
    "default_flag",
    "pl_refname",
    "sy_refname",
    "disc_pubdate",
    "disc_year",
    "discoverymethod",
    "disc_locale",
    "disc_facility",
    "disc_instrument",
    "disc_telescope",
    "disc_refname",
    "ra",
    "rastr",
    "dec",
    "decstr",
    "glon",
    "glat",
    "elon",
    "elat",
    "pl_orbper",
    "pl_orbpererr1",
    "pl_orbpererr2",
    "pl_orbperlim",
    "pl_orbperstr",
    "pl_orblpererr1",
    "pl_orblper",
    "pl_orblpererr2",
    "pl_orblperlim",
    "pl_orblperstr",
    "pl_orbsmax",
    "pl_orbsmaxerr1",
    "pl_orbsmaxerr2",
    "pl_orbsmaxlim",
    "pl_orbsmaxstr",
    "pl_orbincl",
    "pl_orbinclerr1",
    "pl_orbinclerr2",
    "pl_orbincllim",
    "pl_orbinclstr",
    "pl_orbtper",
    "pl_orbtpererr1",
    "pl_orbtpererr2",
    "pl_orbtperlim",
    "pl_orbtperstr",
    "pl_orbeccen",
    "pl_orbeccenerr1",
    "pl_orbeccenerr2",
    "pl_orbeccenlim",
    "pl_orbeccenstr",
    "pl_eqt",
    "pl_eqterr1",
    "pl_eqterr2",
    "pl_eqtlim",
    "pl_eqtstr",
    "pl_occdep",
    "pl_occdeperr1",
    "pl_occdeperr2",
    "pl_occdeplim",
    "pl_occdepstr",
    "pl_insol",
    "pl_insolerr1",
    "pl_insolerr2",
    "pl_insollim",
    "pl_insolstr",
    "pl_dens",
    "pl_denserr1",
    "pl_denserr2",
    "pl_denslim",
    "pl_densstr",
    "pl_trandep",
    "pl_trandeperr1",
    "pl_trandeperr2",
    "pl_trandeplim",
    "pl_trandepstr",
    "pl_tranmid",
    "pl_tranmiderr1",
    "pl_tranmiderr2",
    "pl_tranmidlim",
    "pl_tranmidstr",
    "pl_trandur",
    "pl_trandurerr1",
    "pl_trandurerr2",
    "pl_trandurlim",
    "pl_trandurstr",
    "sy_kmagstr",
    "sy_umag",
    "sy_umagerr1",
    "sy_umagerr2",
    "sy_umagstr",
    "sy_rmag",
    "sy_rmagerr1",
    "sy_rmagerr2",
    "sy_rmagstr",
    "sy_imag",
    "sy_imagerr1",
    "sy_imagerr2",
    "sy_imagstr",
    "sy_zmag",
    "sy_zmagerr1",
    "sy_zmagerr2",
    "sy_zmagstr",
    "sy_w1mag",
    "sy_w1magerr1",
    "sy_w1magerr2",
    "sy_w1magstr",
    "sy_w2mag",
    "sy_w2magerr1",
    "sy_w2magerr2",
    "sy_w2magstr",
    "sy_w3mag",
    "sy_w3magerr1",
    "sy_w3magerr2",
    "sy_w3magstr",
    "sy_w4mag",
    "sy_w4magerr1",
    "sy_w4magerr2",
    "sy_w4magstr",
    "sy_gmag",
    "sy_gmagerr1",
    "sy_gmagerr2",
    "sy_gmagstr",
    "sy_gaiamag",
    "sy_gaiamagerr1",
    "sy_gaiamagerr2",
    "sy_gaiamagstr",
    "sy_tmag",
    "sy_tmagerr1",
    "sy_tmagerr2",
    "sy_tmagstr",
    "pl_controv_flag",
    "pl_tsystemref",
    "st_metratio",
    "st_spectype",
    "sy_kepmag",
    "sy_kepmagerr1",
    "sy_kepmagerr2",
    "sy_kepmagstr",
    "st_rotp",
    "st_rotperr1",
    "st_rotperr2",
    "st_rotplim",
    "st_rotpstr",
    "pl_projobliq",
    "pl_projobliqerr1",
    "pl_projobliqerr2",
    "pl_projobliqlim",
    "pl_projobliqstr",
    "x",
    "y",
    "z",
    "htm20",
    "pl_rvamp",
    "pl_rvamperr1",
    "pl_rvamperr2",
    "pl_rvamplim",
    "pl_rvampstr",
    "pl_radj",
    "pl_radjerr1",
    "pl_radjerr2",
    "pl_radjlim",
    "pl_radjstr",
    "pl_rade",
    "pl_radeerr1",
    "pl_radeerr2",
    "pl_radelim",
    "pl_radestr",
    "pl_ratror",
    "pl_ratrorerr1",
    "pl_ratrorerr2",
    "pl_ratrorlim",
    "pl_ratrorstr",
    "pl_ratdor",
    "pl_trueobliq",
    "pl_trueobliqerr1",
    "pl_trueobliqerr2",
    "pl_trueobliqlim",
    "pl_trueobliqstr",
    "sy_icmag",
    "sy_icmagerr1",
    "sy_icmagerr2",
    "sy_icmagstr",
    "rowupdate",
    "pl_pubdate",
    "st_refname",
    "releasedate",
    "dkin_flag",
    "pl_ratdorerr1",
    "pl_ratdorerr2",
    "pl_ratdorlim",
    "pl_ratdorstr",
    "pl_imppar",
    "pl_impparerr1",
    "pl_impparerr2",
    "pl_impparlim",
    "pl_impparstr",
    "pl_cmassj",
    "pl_cmassjerr1",
    "pl_cmassjerr2",
    "pl_cmassjlim",
    "pl_cmassjstr",
    "pl_cmasse",
    "pl_cmasseerr1",
    "pl_cmasseerr2",
    "pl_cmasselim",
    "pl_cmassestr",
    "pl_massj",
    "pl_massjerr1",
    "pl_massjerr2",
    "pl_massjlim",
    "pl_massjstr",
    "pl_masse",
    "pl_masseerr1",
    "pl_masseerr2",
    "pl_masselim",
    "pl_massestr",
    "pl_bmassj",
    "pl_bmassjerr1",
    "pl_bmassjerr2",
    "pl_bmassjlim",
    "pl_bmassjstr",
    "pl_bmasse",
    "pl_bmasseerr1",
    "pl_bmasseerr2",
    "pl_bmasselim",
    "pl_bmassestr",
    "pl_bmassprov",
    "pl_msinij",
    "pl_msinijerr1",
    "pl_msinijerr2",
    "pl_msinijlim",
    "pl_msinijstr",
    "pl_msinie",
    "pl_msinieerr1",
    "pl_msinieerr2",
    "pl_msinielim",
    "pl_msiniestr",
    "st_teff",
    "st_tefferr1",
    "st_tefferr2",
    "st_tefflim",
    "st_teffstr",
    "st_met",
    "st_meterr1",
    "st_meterr2",
    "st_metlim",
    "st_metstr",
    "st_radv",
    "st_radverr1",
    "st_radverr2",
    "st_radvlim",
    "st_radvstr",
    "st_vsin",
    "st_vsinerr1",
    "st_vsinerr2",
    "st_vsinlim",
    "st_vsinstr",
    "st_lum",
    "st_lumerr1",
    "st_lumerr2",
    "st_lumlim",
    "st_lumstr",
    "st_logg",
    "st_loggerr1",
    "st_loggerr2",
    "st_logglim",
    "st_loggstr",
    "st_age",
    "st_ageerr1",
    "st_ageerr2",
    "st_agelim",
    "st_agestr",
    "st_mass",
    "st_masserr1",
    "st_masserr2",
    "st_masslim",
    "st_massstr",
    "st_dens",
    "st_denserr1",
    "st_denserr2",
    "st_denslim",
    "st_densstr",
    "st_rad",
    "st_raderr1",
    "st_raderr2",
    "st_radlim",
    "st_radstr",
    "ttv_flag",
    "ptv_flag",
    "tran_flag",
    "rv_flag",
    "ast_flag",
    "obm_flag",
    "micro_flag",
    "etv_flag",
    "ima_flag",
    "pul_flag",
    "soltype",
    "sy_snum",
    "sy_pnum",
    "sy_mnum",
    "cb_flag",
    "st_nphot",
    "st_nrvc",
    "st_nspec",
    "pl_nespec",
    "pl_ntranspec",
    "pl_ndispec",
    "pl_nnotes",
    "sy_pm",
    "sy_pmerr1",
    "sy_pmerr2",
    "sy_pmstr",
    "sy_pmra",
    "sy_pmraerr1",
    "sy_pmraerr2",
    "sy_pmrastr",
    "sy_pmdec",
    "sy_pmdecerr1",
    "sy_pmdecerr2",
    "sy_pmdecstr",
    "sy_plx",
    "sy_plxerr1",
    "sy_plxerr2",
    "sy_plxstr",
    "sy_dist",
    "sy_disterr1",
    "sy_disterr2",
    "sy_diststr",
    "sy_bmag",
    "sy_bmagerr1",
    "sy_bmagerr2",
    "sy_bmagstr",
    "sy_vmag",
    "sy_vmagerr1",
    "sy_vmagerr2",
    "sy_vmagstr",
    "sy_jmag",
    "sy_jmagerr1",
    "sy_jmagerr2",
    "sy_jmagstr",
    "sy_hmag",
    "sy_hmagerr1",
    "sy_hmagerr2",
    "sy_hmagstr",
    "sy_kmag",
    "sy_kmagerr1",
    "sy_kmagerr2",
]

ALL_COMPUTED_COLUMNS = [
    "ppld_mass_kg",
    "ppld_mass_kg_err1",
    "ppld_mass_kg_err2",
    "ppld_mass_kg_weight",
    "ppld_radius_m",
    "ppld_radius_m_err1",
    "ppld_radius_m_err2",
    "ppld_radius_m_weight",
    "ppld_density_gcm3_weight",
    "ppld_surf_grav_ms2",
    "ppld_surf_grav_earth",
    "ppld_surf_grav_ms2_err1",
    "ppld_surf_grav_ms2_err2",
    "ppld_surf_grav_earth_err1",
    "ppld_surf_grav_earth_err2",
    "dm_class",
    "dm_pred_g_ms2",
    "dm_pred_g_earth",
    "dm_grav_residual",
]

USUAL_PSCOMPPARS_COLUMNS = [
    "hostname",
    "pl_name",
    "pl_letter",
    #
    "pl_massj",
    "pl_massjerr1",
    "pl_massjerr2",
    "pl_massjformat",
    "pl_massjlim",
    "pl_massj_reflink",
    "pl_massj_solnid",
    "pl_massjstr",
    "pl_massjsymerr",
    #
    "pl_bmassj",
    "pl_bmassjerr1",
    "pl_bmassjerr2",
    "pl_bmassjformat",
    "pl_bmassjlim",
    "pl_bmassj_reflink",
    "pl_bmassj_solnid",
    "pl_bmassjstr",
    "pl_bmassjsymerr",
    "pl_bmassprov",
    #
    "pl_radj",
    "pl_radjerr1",
    "pl_radjerr2",
    "pl_radj_reflink",
    "pl_radjstr",
    "pl_radjlim",
    #
    "pl_rade",
    "pl_radeerr1",
    "pl_radeerr2",
    "pl_rade_reflink",
    "pl_radestr",
    "pl_radelim",
    #
    "pl_dens",
    "pl_denserr1",
    "pl_denserr2",
    "pl_dens_reflink",
    "pl_densstr",
    "pl_denslim",
]

USUAL_PS_COLUMNS = [
    "hostname",
    "pl_name",
    "pl_letter",
    #
    "pl_massj",
    "pl_massjerr1",
    "pl_massjerr2",
    "pl_massjlim",
    "pl_massjstr",
    #
    "pl_bmassj",
    "pl_bmassjerr1",
    "pl_bmassjerr2",
    "pl_bmassjlim",
    "pl_bmassjstr",
    "pl_bmassprov",
    #
    "pl_radj",
    "pl_radjerr1",
    "pl_radjerr2",
    "pl_radjstr",
    "pl_radjlim",
    #
    "pl_rade",
    "pl_radeerr1",
    "pl_radeerr2",
    "pl_radestr",
    "pl_radelim",
    #
    "pl_dens",
    "pl_denserr1",
    "pl_denserr2",
    "pl_denslim",
    "pl_densstr",
]


GROUP_COLOURS = {
    "Identity": "D9EAD3",
    "Discovery": "FCE5CD",
    "Orbit": "CFE2F3",
    "MassJ": "EAD1DC",
    "MassE": "FFD6B0",
    "RadiusJ": "D9D2E9",
    "RadiusE": "C9E1F5",
    "Density": "FFF2CC",
    "Stellar": "F4CCCC",
    "Surface Gravity": "B7E1CD",
    "System": "E9E9E9",
    "DM Class": "D0E0FF",
    "Unknown": "E0E0E0",
}

COLUMN_GROUPS = {
    "pl_name": "Identity",
    "hostname": "Identity",
    "pl_letter": "Identity",
    "discoverymethod": "Discovery",
    "disc_year": "Discovery",
    "disc_facility": "Discovery",
    "pl_orbper": "Orbit",
    "pl_orbpererr1": "Orbit",
    "pl_orbpererr2": "Orbit",
    "pl_orbperstr": "Orbit",
    "pl_orbperlim": "Orbit",
    "pl_orbpern": "Orbit",
    "pl_orbsmax": "Orbit",
    "pl_orbsmaxerr1": "Orbit",
    "pl_orbsmaxerr2": "Orbit",
    "pl_orbsmaxstr": "Orbit",
    "pl_orbsmaxlim": "Orbit",
    "pl_orbsmaxn": "Orbit",
    "pl_orbeccen": "Orbit",
    "pl_orbeccenerr1": "Orbit",
    "pl_orbeccenerr2": "Orbit",
    "pl_orbeccenstr": "Orbit",
    "pl_orbeccenlim": "Orbit",
    "pl_orbeccenn": "Orbit",
    "pl_massj": "MassJ",
    "pl_massjerr1": "MassJ",
    "pl_massjerr2": "MassJ",
    "pl_massjlim": "MassJ",
    "pl_massjstr": "MassJ",
    "pl_masse": "MassE",
    "pl_masseerr1": "MassE",
    "pl_masseerr2": "MassE",
    "pl_masselim": "MassE",
    "pl_massestr": "MassE",
    "pl_bmassj": "MassJ",
    "pl_bmassjerr1": "MassJ",
    "pl_bmassjerr2": "MassJ",
    "pl_bmassjlim": "MassJ",
    "pl_bmassjstr": "MassJ",
    "pl_bmassprov": "MassJ",
    "pl_bmasse": "MassE",
    "pl_bmasseerr1": "MassE",
    "pl_bmasseerr2": "MassE",
    "pl_bmasselim": "MassE",
    "pl_bmassestr": "MassE",
    "pl_cmassj": "MassJ",
    "pl_cmassjerr1": "MassJ",
    "pl_cmassjerr2": "MassJ",
    "pl_cmassjlim": "MassJ",
    "pl_cmassjstr": "MassJ",
    "pl_cmasse": "MassE",
    "pl_cmasseerr1": "MassE",
    "pl_cmasseerr2": "MassE",
    "pl_cmasselim": "MassE",
    "pl_cmassestr": "MassE",
    "pl_msinij": "MassJ",
    "pl_msinijerr1": "MassJ",
    "pl_msinijerr2": "MassJ",
    "pl_msinijlim": "MassJ",
    "pl_msinijstr": "MassJ",
    "pl_msinie": "MassE",
    "pl_msinieerr1": "MassE",
    "pl_msinieerr2": "MassE",
    "pl_msinielim": "MassE",
    "pl_msiniestr": "MassE",
    "pl_radj": "RadiusJ",
    "pl_radjerr1": "RadiusJ",
    "pl_radjerr2": "RadiusJ",
    "pl_radj_reflink": "RadiusJ",
    "pl_radjstr": "RadiusJ",
    "pl_radjlim": "RadiusJ",
    "pl_radn": "RadiusJ",
    "pl_rade": "RadiusE",
    "pl_radeerr1": "RadiusE",
    "pl_radeerr2": "RadiusE",
    "pl_rade_reflink": "RadiusE",
    "pl_radestr": "RadiusE",
    "pl_radelim": "RadiusE",
    "pl_raden": "RadiusE",
    "pl_dens": "Density",
    "pl_denserr1": "Density",
    "pl_denserr2": "Density",
    "pl_dens_reflink": "Density",
    "pl_densstr": "Density",
    "pl_denslim": "Density",
    "pl_densm": "Density",
    "pl_eqt": "Stellar",
    "pl_eqterr1": "Stellar",
    "pl_eqterr2": "Stellar",
    "pl_eqtstr": "Stellar",
    "pl_eqtlim": "Stellar",
    "pl_eqtn": "Stellar",
    "pl_insol": "Stellar",
    "st_teff": "Stellar",
    "st_rad": "Stellar",
    "st_mass": "Stellar",
    "sy_dist": "System",
    "sy_snum": "System",
    "sy_pnum": "System",
    "ppld_mass_kg": "MassJ",
    "ppld_mass_kg_err1": "MassJ",
    "ppld_mass_kg_err2": "MassJ",
    "ppld_radius_m": "RadiusJ",
    "ppld_radius_m_err1": "RadiusE",
    "ppld_radius_m_err2": "RadiusE",
    "ppld_surf_grav_ms2": "Surface Gravity",
    "ppld_surf_grav_earth": "Surface Gravity",
    "ppld_surf_grav_ms2_err1": "Surface Gravity",
    "ppld_surf_grav_ms2_err2": "Surface Gravity",
    "ppld_surf_grav_earth_err1": "Surface Gravity",
    "ppld_surf_grav_earth_err2": "Surface Gravity",
    "dm_class": "DM Class",
    "dm_pred_g_ms2": "DM Class",
    "dm_pred_g_earth": "DM Class",
    "dm_grav_residual": "DM Class",
}

SOLAR_SYSTEM_OBJECTS = """
body,mass_kg,mass_err_plus,mass_err_minus,mass_weight,mass_method,mass_reference,radius_m,radius_err_plus,radius_err_minus,radius_weight,radius_method,radius_reference,density_kg_m3,density_err_plus,density_err_minus,density_method,density_reference,density_weight
Jupiter,1.8982E+027,5E+022,5E+022,0.95,spacecraft_ephemeris,Jacobson et al. (2015/2023) JPL Planetary Ephemerides + Juno gravity solutions,69911000,10000,10000,0.95,occultation+shape,IAU Working Group (2015) Planetary and Satellite Physical Parameters,1326,10,10,GM+radius derived,Iess et al. (2019) Cassini + Juno gravity field; NASA JPL DE440,0.99
Saturn,5.6834E+026,3E+022,3E+022,0.95,spacecraft_gravity,Iess et al. (2019) Cassini Gravity Field and Internal Structure,58232000,10000,10000,0.95,occultation+ring constraints,IAU (2015) + Cassini limb fits,687,12,12,GM+radius derived,Iess et al. (2019) Cassini gravity inversion (Nature),0.99
Neptune,1.02409E+026,5E+021,5E+021,0.95,ephemeris_fit,Jacobson (2014/2023) Neptune System Ephemerides,24622000,20000,20000,0.95,Voyager_occultation,Tyler et al. (1989) Voyager 2 Atmosphere & Radius,1638,30,30,GM+radius derived,Tyler et al. (1989) Voyager 2 + JPL ephemerides,0.97
Uranus,8.681E+025,5E+021,5E+021,0.95,ephemeris_fit,Jacobson (2014/2023) Uranian System Ephemerides,25362000,7000,7000,0.95,Voyager+astrometry,Lindal et al. (1987) Voyager Radio Occultation,1270,40,40,GM+radius derived,Lindal et al. (1987) Voyager occultation + Jacobson ephemeris updates,0.97
Earth,5.97237E+024,1E+020,1E+020,0.95,satellite_geodesy,Petit & Luzum (2010) IERS Conventions + GRACE/GOCE updates,6371010,10,10,0.95,geodetic_reference,NASA/IAU Earth Reference Ellipsoid (WGS84 updates),5514,1,1,geodesy+gravity field,IERS Conventions 2010 + GRACE/GOCE (Petit & Luzum),0.99
Venus,4.8675E+024,1E+020,1E+020,0.95,spacecraft_tracking,Konopliv et al. (1999) Magellan Gravity Field,6051800,10,10,0.95,radar_altimetry,Magellan Radar Mapping + IAU (2015),5243,4,4,radar+tracking derived,Konopliv et al. (1999) Magellan gravity field,0.98
Mars,6.4171E+023,1E+019,1E+019,0.95,orbiter_tracking,Konopliv et al. (2016) MRO/MGS Gravity Field,3389500,50,50,0.95,laser_altimetry,Smith et al. (2001) MOLA Topography,3934,1,1,orbiter gravity model,Konopliv et al. (2016) MRO/MGS gravity field,0.99
Mercury,3.3011E+023,1E+019,1E+019,0.95,spacecraft_tracking,Smith et al. (2012) MESSENGER Gravity Field,2439700,100,100,0.95,radar+imaging,Anderson et al. (2012) MESSENGER Radius Model,5427,3,3,spacecraft gravity,Smith et al. (2012) MESSENGER gravity model,0.99
Ganymede,1.4819E+023,1E+019,1E+019,0.95,galileo_gravity,Anderson et al. (1996) Galileo Ganymede Gravity,2634100,1000,1000,0.95,imaging+limb,Thomas et al. (1998),1942,5,5,spacecraft gravity+shape,Anderson et al. (1996) Galileo gravity field (Icarus),0.98
Titan,1.3452E+023,1E+019,1E+019,0.95,cassini_tracking,Jacobson et al. (2006) Cassini Titan Orbit Solution,2575000,2000,2000,0.95,radar_altimetry,Stiles et al. (2008) Cassini Radar Topography,1881,5,5,cassini tracking+occultation,Jacobson et al. (2006) Cassini orbit determination,0.98
Callisto,1.0759E+023,1E+019,1E+019,0.95,galileo_gravity,Anderson et al. (2001) Callisto Gravity Field,2410300,1000,1000,0.95,imaging,Thomas et al. (1998),1830,5,5,galileo gravity model,Anderson et al. (2001) Galileo Callisto gravity,0.98
Io,8.9319E+022,9E+018,9E+018,0.95,galileo_gravity,Anderson et al. (2001) Galileo Gravity Results,1821600,2000,2000,0.95,imaging+limb_fit,Thomas et al. (1998) Voyager/Galileo shape,3530,10,10,galileo gravity field,Anderson et al. (2001) Io gravity solution,0.98
Moon,7.342E+022,1E+019,1E+019,0.95,LLR+GRAIL,Williams et al. (2014) Lunar Laser Ranging + Zuber et al. (2013) GRAIL,1737400,5,5,0.95,laser_altimetry,LRO LOLA (Smith et al. 2010),3340,2,2,LLR+GRAIL gravity model,Williams et al. (2014) + Zuber et al. (2013 GRAIL Science),0.99
Europa,4.7998E+022,6E+018,6E+018,0.95,galileo_flybys,Anderson et al. (1998) Europa Gravity Field,1560800,2000,2000,0.95,imaging,Schenk & McKinnon (1989/2009 updates),3010,10,10,galileo flyby gravity,Anderson et al. (1998) Europa gravity model,0.98
Triton,2.14E+022,1E+019,1E+019,0.9,voyager_dynamics,Jacobson et al. (1990) Neptune System + Voyager 2,1353400,2000,2000,0.9,imaging,Smith et al. (1989) Voyager 2 Triton Imaging,2060,20,20,voyager dynamics+ephemeris,Jacobson et al. (1990) Neptune system solution,0.95
Eris,1.646E+022,1E+019,1E+019,0.8,orbital_dynamics,Brown & Schaller (2007) Dysnomia Orbit,1163000,6000,6000,0.8,stellar_occultation,Sicardy et al. (2011/2016),2420,200,200,orbital dynamics + occultation,"Sicardy et al. (2011, 2016) stellar occultation",0.8
Pluto,1.303E+022,5E+018,5E+018,0.95,new_horizons_dynamics,Stern et al. (2015) New Horizons Pluto System,1188300,1000,1000,0.95,imaging_occultation,Nimmo et al. (2017) Pluto Radius Model,1854,6,6,new horizons gravity+occultation,Nimmo et al. (2017) Pluto system density,0.99
Haumea,4.006E+021,1E+019,1E+019,0.8,satellite_orbits,Ragozzine & Brown (2009) Hiʻiaka Orbit,715000,20000,20000,0.8,shape_model,Lockwood et al. (2014) Lightcurve Modeling,1880,120,120,shape + satellite orbit,Ragozzine & Brown (2009) + Lockwood et al. (2014),0.85
Titania,3.527E+021,1E+018,1E+018,0.8,voyager_dynamics,Jacobson (1992) Uranian Moons Dynamics,789000,2000,2000,0.8,imaging,Thomas (1988 Voyager 2 Uranus),1710,30,30,voyager gravity estimate,Jacobson (1992) Uranian system dynamics,0.9
Makemake,3.1E+021,1.5E+021,1.5E+021,0.5,thermal_model,Ortiz et al. (2012) Stellar Occultation + Albedo,710000,30000,30000,0.5,occultation_single,Ortiz et al. (2012),1900,300,300,thermal model + albedo constraint,Ortiz et al. (2012) stellar occultation,0.7
Oberon,3.014E+021,1E+018,1E+018,0.8,voyager_dynamics,Jacobson (1992),761000,2000,2000,0.8,imaging,Smith et al. (1986),1630,30,30,voyager dynamics,Jacobson (1992),0.9
Sedna,3E+021,2E+021,2E+021,0.2,albedo_assumption,Brown et al. (2004) Discovery Paper (no mass constraint),550000,50000,50000,0.2,assumed_model,Brown et al. (2004),>1000?,,,assumed from composition models,Brown et al. (2004 discovery; no dynamical mass constraint,0.2
Rhea,2.306E+021,1E+018,1E+018,0.8,cassini_tracking,Jacobson et al. (2006 Saturn Moons,763000,1000,1000,0.8,imaging,Thomas et al. (2007 Cassini),1233,20,20,cassini gravity field,Jacobson et al. (2006) Saturn system,0.92
Iapetus,1.805E+021,1E+018,1E+018,0.8,cassini_tracking,Jacobson et al. (2006),735000,1000,1000,0.8,imaging,Thomas et al. (2007),1085,30,30,cassini tracking,Jacobson et al. (2006),0.9
Gonggong,1.75E+021,7E+020,7E+020,0.5,satellite_dynamics,Fraser et al. (2016) Xiangliu Orbit,615000,20000,20000,0.5,thermal_model,Lellouch et al. (2010s TNO surveys),1900,300,300,satellite orbit + thermal,Fraser et al. (2016) Xiangliu system,0.7
Charon,1.586E+021,1E+018,1E+018,0.95,pluto_barycenter_dynamics,Buie et al. (2018) New Horizons System Dynamics,606300,10,10,0.95,imaging_occultation,Nimmo et al. (2017),1855,5,5,pluto system dynamics,Buie et al. (2018) New Horizons system solution,0.99
Quaoar,1.4E+021,1E+019,1E+019,0.8,satellite_orbit,Fraser & Brown (2010) Weywot Orbit,555000,2000,2000,0.8,stellar_occultation,Braga-Ribas et al. (2013),1975,50,50,satellite orbit + occultation,Braga-Ribas et al. (2013),0.88
Ariel,1.353E+021,1E+018,1E+018,0.8,voyager_dynamics,Jacobson (1992),579000,2000,2000,0.8,imaging,Smith et al. (1986),1660,30,30,voyager gravity,Jacobson (1992),0.9
Umbriel,1.172E+021,1E+018,1E+018,0.8,voyager_dynamics,Jacobson (1992),584000,2000,2000,0.8,imaging,Smith et al. (1986),1400,30,30,voyager gravity,Jacobson (1992),0.9
Dione,1.095E+021,1E+018,1E+018,0.8,cassini_tracking,Jacobson et al. (2006),561000,1000,1000,0.8,imaging,Thomas et al. (2007),1470,20,20,cassini tracking,Jacobson et al. (2006),0.92
Ceres,9.3835E+020,1E+017,1E+017,0.95,dawn_gravity,Park et al. (2019) Dawn Ceres Gravity Field,473500,200,200,0.95,laser_altimetry,Russell et al. (2016) Dawn Shape Model,2162,5,5,dawn gravity field,Park et al. (2019) Dawn mission gravity model,0.99
Orcus,6.32E+020,1E+018,1E+018,0.8,satellite_orbit,Brown et al. (2010) Vanth Orbit,450000,1000,1000,0.8,occultation+imaging,Sicardy et al. (2011),1900,100,100,satellite orbit,Brown et al. (2010) Vanth orbit solution,0.85
Tethys,6.174E+020,1E+018,1E+018,0.8,cassini_tracking,Jacobson et al. (2006),531000,1000,1000,0.8,imaging,Thomas et al. (2007),984,30,30,cassini tracking,Jacobson et al. (2006),0.9
Salacia,4E+020,1E+019,1E+019,0.7,satellite_orbit,Johnson et al. (2019) Actaea Orbit,420000,20000,20000,0.7,thermal_model,Vilenius et al. (2012),1000,200,200,thermal + satellite orbit,Vilenius et al. (2012),0.75
Vesta,2.59E+020,1E+017,-1E+017,0.95,dawn spacecraft,"Konopliv et al. (2014) The Vesta gravity field, spin pole, and rotation period from the Dawn spacecraft",262300,100,100,0.95,dawn spacecraft,Ermakov et al. (2014 / 2017) Constraints on Vesta’s interior structure using Dawn gravity and shape models,3450,10,10,dawn gravity + shape,Konopliv et al. (2014) Icarus Dawn gravity model,0.99
"""

df_sso = pd.read_csv(StringIO(SOLAR_SYSTEM_OBJECTS))
